admin_task:
  description: >
    Talk to user and provide information to researcher
  expected_output: >
    A concise of question that user ask
  agent: admin
  output_file: output/question.md
  
research_task:
  description: >
    Conduct a thorough research throughout {spec} when receive question from user
    Make sure you find any interesting and relevant information given
    and only provide information that has mention in {spec} say you don't know
    if you cannot find information in {spec}
  expected_output: >
    A list of the most relevant information about question from user you find in {spec}
    and source reference for each information you found
  agent: spec_researcher
  context:
    - admin_task
  output_file: output/research.md

reporting_task:
  description: >
    Analyze the research finding and do a summary report with reference to source
  expected_output: >
    A fully fledged report to answer the question from user
  agent: spec_analyst
  context:
    - research_task
  output_file: output/summary.md
